# Generated by Django 3.2.8 on 2021-11-06 23:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='epion_offices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epion_practice_id', models.IntegerField()),
                ('launched_date', models.DateField(blank=True, default=None, null=True)),
                ('disabled_date', models.DateField(blank=True, default=None, null=True)),
                ('emr_department_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=None)),
                ('office_name', models.TextField()),
            ],
            options={
                'db_table': 'epion_offices',
            },
        ),
        migrations.CreateModel(
            name='epion_practices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.TextField()),
                ('emr_practice_id', models.IntegerField()),
                ('epion_practice_id', models.IntegerField()),
            ],
            options={
                'db_table': 'epion_practices',
            },
        ),
    ]
